Restore the mender-connect dependency and re-enable test
mendersoftware/mender-dist-packages pull request #188
Opened 2022-02-04 13:44 UTC by oleorhagen

Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2022-02-07 07:43 UTC, lluiscampos requested changes
[This fixture](https://github.com/mendersoftware/mender-dist-packages/blob/master/tests/conftest.py#L97-L101) is what you need to update for the addon tests to install a given version of the client.

2022-02-07 07:43 UTC, lluiscampos commented on recipes/mender-connect/debian-master/control
> +Depends: mender-client (>3.2.0), ${shlibs:Depends}, ${misc:Depends}
This is not strictly speaking necessary, but a nice clean-up IMO.

2022-02-07 08:49 UTC, lluiscampos commented
Actually the JIRA task was a bit off in the description (because the original PR got force-pushed), but the original commit to revert is [this one](https://github.com/mendersoftware/mender-dist-packages/pull/147/commits/42e4e97291d7f5929f32b3eb23dc98caa059f160).

2022-02-08 10:10 UTC, oleorhagen commented
> Actually the JIRA task was a bit off in the description (because the original PR got force-pushed), but the original commit to revert is [this one](https://github.com/mendersoftware/mender-dist-packages/pull/147/commits/42e4e97291d7f5929f32b3eb23dc98caa059f160).

:+1: 

  https://github.com/mendersoftware/mender-docs/pull/1655

2022-02-08 13:07 UTC, lluiscampos approved these changes

2022-02-08 13:08 UTC, lluiscampos commented
Looks good!

I am sorry I have introduced a merge conflict from another PR :smile_cat:

2022-02-08 19:46 UTC, lluiscampos commented
:thinking: I think you need to cherry-pick this one:
* https://github.com/mendersoftware/mender-dist-packages/pull/190

Because the new packages have now this `+debian+buster` prefix.

2022-02-09 09:01 UTC, oleorhagen commented
> thinking I think you need to cherry-pick this one:
> 
>     * [Changelog:All: Bump tests/mender_test_containers from `87e4fe7` to `5358b6c` #190](https://github.com/mendersoftware/mender-dist-packages/pull/190)
> 
> 
> Because the new packages have now this `+debian+buster` prefix.

Ahh, nice. Fix is already in. I was planning on looking at this today :raised_hands:

2022-02-14 13:22 UTC, merged