fix: Explicitly upload the deb_package to the /latest/ bucket
mendersoftware/mender-dist-packages pull request #36
Opened 2020-10-26 13:11 UTC by oleorhagen

While also giving it the name latest.

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

2020-10-26 13:12 UTC, oleorhagen commented on .gitlab-ci.yml
> +          --key ${MENDER_VERSION}/${S3_BUCKET_SUBPATH}/${arch}/mender-client_${deb_version}_${arch}.deb;
I am unsure as to whether or not this should be:
```suggestion
          --key ${MENDER_VERSION}/${S3_BUCKET_SUBPATH}/${arch}/mender-client_latest_${arch}.deb;
```
or something else?

2020-10-26 13:28 UTC, lluiscampos requested changes

2020-10-26 13:28 UTC, lluiscampos commented on .gitlab-ci.yml
> +          --key ${MENDER_VERSION}/${S3_BUCKET_SUBPATH}/${arch}/mender-client_${deb_version}_${arch}.deb;
The ACL needs to be applied to the same path as the file:

```suggestion
          --key latest/${S3_BUCKET_SUBPATH}/${arch}/mender-client_latest_${arch}.deb;
```

2020-10-26 13:29 UTC, oleorhagen commented on .gitlab-ci.yml
> +          --key ${MENDER_VERSION}/${S3_BUCKET_SUBPATH}/${arch}/mender-client_${deb_version}_${arch}.deb;
https://github.com/mendersoftware/mender-dist-packages/pull/36#discussion_r511958182

2020-10-26 13:39 UTC, lluiscampos approved these changes
I think it looks good :crossed_fingers: 

Sorry I didn't catch this previously.

2020-10-26 13:40 UTC, oleorhagen commented
No worries. This one took me a while to comprehend.

2020-10-26 13:52 UTC, oleorhagen commented
Also, @lluiscampos for a patch release, like I am doing now, this will have to be disabled, or at least the user should be aware of this, so that for this release, this does not wind up pointing to `2.3.1`.

2020-10-26 14:22 UTC, lluiscampos commented
> Also, @lluiscampos for a patch release, like I am doing now, this will have to be disabled, or at least the user should be aware of this, so that for this release, this does not wind up pointing to `2.3.1`.

That is an really good catch, @oleorhagen. As we just discussed in person, we need to go back to the drawing table a bit... The design should have been something like:
* `mender` repo figures out if the tag under test is the latest or not. If so, add an special variable to the [mender-dist-packages trigger](https://github.com/mendersoftware/mender/blob/master/.gitlab-ci.yml#L87).
* `mender-dist-packages` pipeline just accepts an extra env variable `PUBLISH_LATEST` or something like that for which to publish the latest package blindly.

Does it make sense?

The code for the actual publish I think is correct in this PR, is only that the `only` part of the job should now use a new env variable.

2020-10-27 09:11 UTC, lluiscampos requested changes

2020-10-27 09:11 UTC, lluiscampos commented on .gitlab-ci.yml
> +      - $PUBLISH_LATEST_CLIENT_PACKAGE == "true"
Please add the variable (optionally with a doc string) at the beginning of the pipeline, in `variables` section, with default falue `false`. Keep in mind that we might need to trigger it manually some times so it is good to have it at the top.

2020-10-27 11:47 UTC, oleorhagen commented
@lluiscampos should be good

2020-10-27 13:34 UTC, lluiscampos approved these changes

2020-10-27 14:04 UTC, merged