MEN-6858: Update `Depends` for next `mender-connect` release
mendersoftware/mender-dist-packages pull request #375
Opened 2023-11-28 12:20 UTC by lluiscampos

Which will require `mender-client` 4.0 or newer due to the systemd
service rename. See related change:
* https://github.com/mendersoftware/mender-connect/pull/119

2023-11-28 12:21 UTC, lluiscampos commented
The first commit has no code changes. Best reviewed with: `git show -C -C 90a1d1`

2023-11-29 04:07 UTC, kacf requested changes

2023-11-29 04:07 UTC, kacf commented on recipes/mender-connect/debian-master/control
> +Depends: mender-client (>4.0.0), ${shlibs:Depends}, ${misc:Depends}
mender-auth, not mender-client, right?

2023-11-30 13:38 UTC, kacf commented on recipes/mender-connect/debian-master/control
> +Depends: mender-client (>4.0.0), ${shlibs:Depends}, ${misc:Depends}
From [this page](https://www.debian.org/doc/debian-policy/ch-relationships.html):

> the package names listed may also include lists of alternative package names, separated by vertical bar (pipe) symbols

Sounds exactly like what we need, doesn't it?

2023-12-04 12:51 UTC, merged